name: Build RNNoise Windows

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Visual Studio Build Tools
        run: choco install visualstudio2019buildtools --yes

      - name: Compile RNNoise
        shell: cmd
        run: |
          cd rnnoise
          cl /EHsc /O2 *.c /link /OUT:rnnoise.exe

      - name: Upload exe
        uses: actions/upload-artifact@v4
        with:
          name: rnnoise-exe
          path: rnnoise/rnnoise.exe
